name: CI

on:
  push:
    branches: [ main ]

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Checks with blacks, isort
    container: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: |
          pip install -r requirements.txt
          ls -la

      - name: Black check
        run:
          black --check .

      - name: Isort check
        run:
          isort --check .


  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: code_quality
    outputs:
      get_release_url: ${{ steps.set_release_url.outputs.release_url }}
      get_current_tag: ${{ steps.set_current_tag_id.outputs.current_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.REPOS_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPOS_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}

      - name: Set Release URL
        id: set_release_url
        run: echo "::set-output name=release_url::${{ steps.create_release.outputs.upload_url }}"

      - name: Set tag version to output
        id: set_current_tag_id
        run: echo "::set-output name=current_tag::${{ steps.tag_version.outputs.new_tag }}"

      - name: Step To run on failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>!!! FAILED !!!</b>
            <b>Failed job:</b> https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}


  build:
    name: Build packages
    needs: release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: python -m PyInstaller --workpath /tmp/build --specpath /tmp -F butler.py
            OUT_FILE_NAME: butler.exe
            ASSET_MIME: application/vnd.microsoft.portable-executable
          - os: ubuntu-latest
            TARGET: ubuntu
            CMD_BUILD: python -m PyInstaller --workpath /tmp/build --specpath /tmp -F butler.py
            OUT_FILE_NAME: butler
            ASSET_MIME: application/x-binary

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build with pyinstaller for ${{ matrix.TARGET }}
        run: ${{ matrix.CMD_BUILD }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.OUT_FILE_NAME }}
          path: ./dist/${{ matrix.OUT_FILE_NAME }}
          retention-days: 1

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.get_release_url }}
          asset_path: ./dist/${{ matrix.OUT_FILE_NAME }}
          asset_name: ${{ matrix.OUT_FILE_NAME }}
          asset_content_type: ${{ matrix.ASSET_MIME }}

      - name: Step To run on failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>!!! FAILED !!!</b>
            <b>Failed job:</b> https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}


  telegram:
    runs-on: ubuntu-latest
    name: Notification
    needs: [ release, build ]

    steps:
      - name: Notify telegram message after Released
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ${{ github.actor }} created commit:

            <b>WorkFlows:</b> <a href="https://github.com/${{ github.repository }}/actions">ActionsList</a>

            Commit with tag: ${{ needs.release.outputs.get_current_tag }}

            Repository: ${{ github.repository }}

            Branch: ${{ github.ref }}

            <b>Release URL:</b> https://github.com/${{ github.repository }}/releases/tag/${{ needs.release.outputs.get_current_tag }}

            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
