name: Code Quality

on:
  push:
    branches: [ feature/* ]

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Checks with black and isort
    container: python:3.9

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: pip install -r requirements.txt

      - name: Black check
        run: black --check .

      - name: Isort check
        run: isort --check .

      - name: Notify if failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>!!! FAILED !!!</b>
            <b>Failed job:</b> https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}

  create_pull_request:
    runs-on: ubuntu-latest
    name: Create Pull Request to develop

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create PR to develop
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.REPOS_TOKEN }}
          source_branch: ""
          destination_branch: "develop"
          pr_title: Automated pull request to develop
          pr_body: "**Automated pull request**"
          pr_assignee: ${{ github.actor }}
          pr_label: develop

      - name: Notify if failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>!!! FAILED !!!</b>
            <b>Failed job:</b> https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}