name: Code Quality

on:
  push:
    branches: [ feature/* ]

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Checks with black and isort
    container: python:3.9

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: pip install -r requirements.txt

      - name: Black check
        run: black --check .

      - name: Isort check
        run: isort --check .

      - name: Notify if failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>!!! FAILED !!!</b>
            <b>Failed job:</b> https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
