name: Code Quality

on:
  push:
    branches: [ feature/* ]

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Checks with black and isort
    container: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: pip install -r requirements.txt

      - name: Black check
        run: black --check .

      - name: Isort check
        run: isort --check .

      - name: Notify if failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>!!! FAILED !!!</b>
            <b>Failed job:</b> https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}

  create_pull_request:
    runs-on: ubuntu-latest
    needs: code_quality
    name: Create Pull Request to develop

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get branch name
        id: branch_name
        uses: tj-actions/branch-names@v5.2

      - name: Running on the default branch.
        if: steps.branch-name.outputs.is_default == 'true'
        run: |
          echo "Running on default: ${{ steps.branch_name.outputs.current_branch }}"

      - name: Create PR to develop
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.REPOS_TOKEN }}
          source_branch: ${{ steps.branch_name.outputs.current_branch }}
          target_branch: develop
          title: Automated pull request to develop
          body: "**Automated pull request**"
          reviewer: ${{ github.actor }}
          assignee: ${{ github.actor }}
          label: develop
          get_diff: true

      - name: Notify if failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>!!! FAILED !!!</b>
            <b>Failed job:</b> https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}