name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Checks with black, isort
    container: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          pip install -r requirements.txt
          ls -la
          black --check .
          isort --check .